# Generated by Django 5.2.7 on 2025-10-07 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='OIDCProfile',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('sub', models.CharField(max_length=255)),
                        ('iss', models.TextField(null=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_profile', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'home_oidcprofile',
                        'constraints': [models.UniqueConstraint(fields=('iss', 'sub'), name='unique_iss_sub')],
                    },
                ),
            ]
        )
    ]
