# Generated by Django 3.1.3 on 2020-11-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_url',
        ),
        migrations.AddField(
            model_name='project',
            name='project_demo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_repository_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
