# Generated by Django 5.0.4 on 2024-09-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_achievement_blogpost_hidden_project_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
