# Generated by Django 5.0.4 on 2024-09-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_achievement_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_board_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
