# Generated by Django 5.2.5 on 2025-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_achievement_id_alter_blogpost_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='cert_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='cert_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
