# Generated by Django 5.2.7 on 2025-11-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('platform_message_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_message_public', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField()),
                ('processed', models.DateTimeField(auto_now_add=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'platform_message_id'), name='unique_platform_platform_message_id')],
            },
        ),
    ]
