# Generated by Django 5.2.7 on 2025-11-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsorship_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='platform_transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
