# Generated by Django 5.0.4 on 2024-09-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201112_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=200)),
                ('achievement_body', models.TextField(blank=True, default='')),
                ('achievement_url', models.URLField(blank=True, default='')),
                ('achievement_date', models.DateField()),
                ('achievement_issuer', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_demo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_repository_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
