# Generated by Django 5.0.4 on 2024-11-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_project_project_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative_name', models.CharField(max_length=200)),
                ('initiative_alt_name', models.CharField(max_length=200)),
                ('initiative_body', models.TextField(blank=True, default='')),
                ('congress_url', models.URLField(blank=True, default='')),
                ('petition_url', models.URLField(blank=True, default='')),
                ('date_introduced', models.DateField()),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='is_activism_tool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_download_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
