# Generated by Django 5.0.4 on 2024-11-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_initiative_project_is_activism_tool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='initiative_alt_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
