# Generated by Django 5.2.5 on 2025-08-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_initiative_initiative_alt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('date_issued', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=200, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=200)),
                ('date_issued', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=200, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
