# Generated by Django 5.2.5 on 2025-08-14 20:08

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_project_image_url_alter_project_project_board_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='preview_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_body',
            field=tinymce.models.HTMLField(),
        ),
    ]
