# Generated by Django 5.2.5 on 2025-08-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_blogpost_preview_text_alter_blogpost_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employer', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
