# Generated by Django 5.2.5 on 2025-08-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('fa_css', models.CharField(blank=True, max_length=100, null=None)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='home.tag'),
        ),
        migrations.AddField(
            model_name='certification',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='home.tag'),
        ),
        migrations.AddField(
            model_name='education',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='educations', to='home.tag'),
        ),
        migrations.AddField(
            model_name='experience',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='home.tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='home.tag'),
        ),
    ]
