# Generated by Django 5.2.5 on 2025-08-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_oidcprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
