# Generated by Django 5.2.5 on 2025-09-06 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_oidcprofile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcprofile',
            name='iss',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oidcprofile',
            name='sub',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='oidcprofile',
            constraint=models.UniqueConstraint(fields=('iss', 'sub'), name='unique_iss_sub'),
        ),
    ]
