# Generated by Django 5.2.7 on 2025-10-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_oidcprofile_iss_alter_oidcprofile_sub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
