# Generated by Django 5.2.7 on 2025-10-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_blogpost_pinned_project_pinned'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='OIDCProfile',
                ),
            ]
        )
    ]
