# Generated by Django 6.0 on 2026-01-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_delete_oidcprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='trainings', to='home.tag')),
            ],
        ),
    ]
