"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os, sys
from decouple import config, Csv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='.localhost', cast=Csv())

# FIXING CSRF ISSUE 
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  
# https://stackoverflow.com/a/71482883/1615284 
# https://docs.djangoproject.com/en/5.1/ref/settings/#secure-proxy-ssl-header

USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'home.apps.HomeConfig',
    'api.apps.APIConfig',
    'users.apps.UsersConfig',
    'portfolio.apps.CustomAdminConfig',
    'django.contrib.auth',
    'mozilla_django_oidc',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'rest_framework',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # https://django-axes.readthedocs.io/en/stable/2_installation.html
]

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.global_settings',  # custom context processor
                'users.context_processors.global_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': config('DATABASE_PATH'),  # Changed for Docker
    }
}


# Auth
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # https://django-axes.readthedocs.io/en/stable/2_installation.html
    'users.auth_backends.CustomOIDCAuthenticationBackend',  # https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#add-settings-to-settings-py
    'django.contrib.auth.backends.ModelBackend',
]

# https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#acquire-a-client-id-and-client-secret

OIDC_RP_CLIENT_ID = config('OIDC_RP_CLIENT_ID', default=None)
OIDC_RP_CLIENT_SECRET = config('OIDC_RP_CLIENT_SECRET', default=None)
OIDC_RP_SIGN_ALGO = config('OIDC_RP_SIGN_ALGO', default=None)

OIDC_OP_JWKS_ENDPOINT = config('OIDC_OP_JWKS_ENDPOINT', default=None)
OIDC_OP_AUTHORIZATION_ENDPOINT = config('OIDC_OP_AUTHORIZATION_ENDPOINT', default=None)
OIDC_OP_TOKEN_ENDPOINT = config('OIDC_OP_TOKEN_ENDPOINT', default=None)
OIDC_OP_USER_ENDPOINT = config('OIDC_OP_USER_ENDPOINT', default=None)

OIDC_OP_DISPLAY_NAME = config('OIDC_OP_DISPLAY_NAME', default=None)
OIDC_CONFIGURED = all([OIDC_RP_CLIENT_ID, OIDC_RP_CLIENT_SECRET])

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Axes
# https://django-axes.readthedocs.io/en/stable/4_configuration.html
AXES_ENABLED = config('AXES_ENABLED', False)
AXES_IPWARE_PROXY_COUNT = config('AXES_IPWARE_PROXY_COUNT', None)
AXES_IPWARE_META_PRECEDENCE_ORDER = config(
    'AXES_IPWARE_META_PRECEDENCE_ORDER',
    cast=Csv(),
    default='HTTP_X_FORWARDED_FOR,X_FORWARDED_FOR',
)
AXES_FAILURE_LIMIT = config('AXES_FAILURE_LIMIT', 5)

# Login redirect
LOGIN_REDIRECT_URL = 'home:index'
LOGOUT_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# Static URL definition
STATIC_URL = '/static/'

# Static file collection directory, served on production. NOT TO BE CONFUSED WITH /static/ (the directory)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional static file sources
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # storing global styles
]
#STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# LOGGING https://docs.djangoproject.com/en/5.1/howto/logging/
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
        }
    }
}

# ADSENSE CLIENT (publisher ID)
ADSENSE_CLIENT = config('ADSENSE_CLIENT', default=None)

# Turnstile
TURNSTILE_SITE_KEY = config('TURNSTILE_SITE_KEY', default=None)
TURNSTILE_SECRET_KEY = config('TURNSTILE_SECRET_KEY', default=None)
TURNSTILE_CONFIGURED = all([TURNSTILE_SITE_KEY, TURNSTILE_SECRET_KEY])
