name: Testing and Deploying (CI/CD)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --file Dockerfile.prod .
  redeploy:
    runs-on: ubuntu-latest
    needs: [build_docker_image]
    if: github.event_name == 'push'
    steps:
      - name: Trigger deployment webhook
        run: |
          printf '{"event": "push-to-main"}' > payload.json
          hash=$(openssl dgst -sha256 -hmac "${{ secrets.WEBHOOK_SECRET }}" payload.json)
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: sha256=$hash" \
          -d @payload.json \
          ${{ secrets.WEBHOOK_URL }}